# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Juan Medrano
tagline:          'Physical AI and Robotics'
description:      'Expertise in robotics engineering with a focus on computer vision and manipulation'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Juan Medrano'
  url:            https://www.linkedin.com/in/jfmygt/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/juanmed

linkedin:
   url:            https://www.linkedin.com/in/jfmygt/

plugins:
  - jekyll-paginate
paginate: 5